name: Lint GitHub Actions

on:
  pull_request:
    paths:
      - '.github/workflows/**'
  push:
    paths:
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install actionlint
        run: |
          curl -o actionlint.tar.gz -L "https://github.com/rhymond/actionlint/releases/latest/download/actionlint_1.7.3_linux_amd64.tar.gz"
          tar -xzf actionlint.tar.gz actionlint
          sudo mv actionlint /usr/local/bin/actionlint
          actionlint -version
          
      - name: Run actionlint
        run: actionlint