name: Semantic Version Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type (leave empty for automatic detection based on conventional commits)'
        required: false
        type: choice
        options:
          - ''
          - 'patch'
          - 'minor'
          - 'major'
        default: ''

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'
          architecture: 'x64'
          cache: false

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: |
          flutter analyze
          flutter test

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install semantic-release dependencies
        run: |
          npm install -g semantic-release @semantic-release/changelog @semantic-release/git conventional-changelog-conventionalcommits

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Create semantic-release config
        run: |
          cat > .releaserc.json << 'EOF'
          {
            "branches": ["master"],
            "plugins": [
              ["@semantic-release/commit-analyzer", {
                "preset": "conventionalcommits"
              }],
              ["@semantic-release/release-notes-generator", {
                "preset": "conventionalcommits"
              }],
              ["@semantic-release/changelog", {
                "changelogFile": "CHANGELOG.md"
              }],
              ["@semantic-release/exec", {
                "prepareCmd": "sed -i 's/version: .*/version: ${nextRelease.version}/' pubspec.yaml"
              }],
              ["@semantic-release/git", {
                "assets": ["CHANGELOG.md", "pubspec.yaml"],
                "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
              }],
              ["@semantic-release/github", {
                "successComment": false,
                "failComment": false,
                "releasedLabels": false
              }]
            ]
          }
          EOF

      - name: Run semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -n "${{ github.event.inputs.release_type }}" ]; then
            echo "Manual release type specified: ${{ github.event.inputs.release_type }}"
            case "${{ github.event.inputs.release_type }}" in
              "patch")
                npx semantic-release --no-ci --debug --force-release patch
                ;;
              "minor")
                npx semantic-release --no-ci --debug --force-release minor
                ;;
              "major")
                npx semantic-release --no-ci --debug --force-release major
                ;;
            esac
          else
            echo "Automatic release type detection based on conventional commits"
            npx semantic-release --no-ci --debug
          fi

      - name: Verify package
        run: dart pub publish --dry-run

      - name: Summary
        run: |
          echo "## Release Summary" >> $GITHUB_STEP_SUMMARY
          echo "✅ Semantic versioning completed successfully" >> $GITHUB_STEP_SUMMARY
          echo "📦 Package validated and ready for publishing" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Next Steps:**" >> $GITHUB_STEP_SUMMARY
          echo "1. Review the generated release and changelog" >> $GITHUB_STEP_SUMMARY
          echo "2. Use the publish workflow to deploy to pub.dev" >> $GITHUB_STEP_SUMMARY