name: Unit tests

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.6
      - run: flutter pub get
      - run: flutter test