name: Unit tests

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'
          architecture: 'x64'
          cache: false
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Verify dependencies
        run: flutter pub deps
        
      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .
        
      - name: Analyze code
        run: flutter analyze
        
      - name: Run tests
        run: flutter test --coverage
        
      - name: Check publish warnings
        run: dart pub publish --dry-run
        
      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        if: github.event_name == 'pull_request'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info
          fail_ci_if_error: false

  validate-workflows:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup actionlint
        run: |
          go install github.com/rhymond/actionlint@latest
          
      - name: Run actionlint
        run: ~/go/bin/actionlint